#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

ctrlc()
{
  restore_animation_speed
  exit
}

set_animation_speed(){
  adb -s $SELECTED_DEVICE shell settings put global animator_duration_scale $1
  adb -s $SELECTED_DEVICE shell settings put global transition_animation_scale $1
  adb -s $SELECTED_DEVICE shell settings put global window_animation_scale $1
}

restore_animation_speed(){
  set_animation_speed 1
  echo "⚡️ Animation speed restored to default."
}

slow_animation_speed(){
  set_animation_speed 10
  read -p "🐌 Slow animations, hit ENTER to stop."
}

if ! [ -z $1 ]; then
  set_animation_speed $1
  read -p "⚡️ Animation scale set to $1 (bigger is slower), hit ENTER to stop."
else
  slow_animation_speed
fi

restore_animation_speed
