#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

if [[ "$1" != "" ]];
then
    PACKAGE_NAME=$1
else
    PACKAGE_NAME=$(adb -s $SELECTED_DEVICE shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)
fi

adb -s $SELECTED_DEVICE shell am start -a "android.settings.APPLICATION_DETAILS_SETTINGS" -d "package:$PACKAGE_NAME" &> /dev/null

VERSION=$(adb -s $SELECTED_DEVICE shell dumpsys package $PACKAGE_NAME | grep versionName | sed 's/versionName=//')
VERSION=`echo $VERSION | awk '{print $1}'` # Remove ghost whitespaces
LAST_UPDATE=$(adb -s $SELECTED_DEVICE shell dumpsys package $PACKAGE_NAME | grep lastUpdateTime | sed 's/lastUpdateTime=//')
LAST_UPDATE=`echo $LAST_UPDATE | awk '{print $1}'` # Remove ghost whitespaces
SDK=$(adb -s $SELECTED_DEVICE shell dumpsys package com.thefuntasty.grason.dev | grep versionCode | grep -o 'minSdk.*')

echo "Package name: $PACKAGE_NAME"
echo "Version: $VERSION"
echo "Last update: $LAST_UPDATE"
echo "SDK: $SDK"
adb -s $SELECTED_DEVICE shell dumpsys package com.thefuntasty.grason.dev | grep  -v "):\|perm=\|installPermissionsFixed=true" |grep -i -e permission
