#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

should_proceed "🔥 Delete all third party apps on $SELECTED_DEVICE?"

IFS=$'\n' #MAGIC
PACKAGES=($(adb -s $SELECTED_DEVICE shell 'pm list packages -3 -f' | sed -e 's/.*=//' | sort))
unset IFS #MAGIC

for PKG in "${PACKAGES[@]}"
do

   if [[ $PKG = *"funtaster"* ]] || [[ $PKG = *"io.crash.air"* ]] || [[ $PKG = *"de.codenauts.hockeyapp"* ]] || [[ $PKG = *"chrome"* ]]; then
      echo "⌛️ Skipping $PKG"
      continue
   fi

   PKG=${PKG%$'\r'} #removes trailing \r
   echo "🔥 Uninstalling $PKG"
   adb -s $SELECTED_DEVICE shell "pm uninstall $PKG" &> /dev/null

done

should_proceed "🔥 Do you want to empty /sdcard/Download?"
echo "🔥 Clearing /sdcard/Download"
adb -s $SELECTED_DEVICE shell rm -r /sdcard/Download/*
echo "✅ Device is now clean."
