#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
android_choose_device

if [ -z "$1" ] ; then
  echo "🤷‍ What should I install?"
  exit
fi

#get package name from .apk
echo "🔍 Detecting package name..."
AAPPT_PATH=$(find $ANDROID_HOME -name 'aapt' | sort | tail -1)
PACKAGE_NAME=$($AAPPT_PATH dump badging $1 | grep package:\ name);
PACKAGE_NAME=$(echo $PACKAGE_NAME | sed 's/^[^'\'']*'\''//');
PACKAGE_NAME=$(echo $PACKAGE_NAME | sed 's/'\''.*//');

echo "⌛️ Installing $PACKAGE_NAME"
adb -s $SELECTED_DEVICE install -r $1 &> /dev/null
if [ $? -eq 0 ] ; then #does not work, exit code is 0 after failure :/
  echo "🚀 Launching..."
  adb -s $SELECTED_DEVICE shell monkey -p $PACKAGE_NAME -c android.intent.category.LAUNCHER 1 &> /dev/null
else
  echo "💥 Installation failed, nothing to launch!"
fi
