#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
choose_device

echo "⚙️ Launching system settings app..."
adb -s $SELECTED_DEVICE shell am start -a android.settings.SETTINGS &> /dev/null
