#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
android_choose_device

app=$(adb -s $SELECTED_DEVICE shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)

read -r -p "🔥 Do you really want to remove all data of $app [y/n] " response
case "$response" in
    [yY])
        ;;
    *)
        exit
        ;;
esac

adb -s $SELECTED_DEVICE shell pm clear $app
echo Relaunching $app
adb -s $SELECTED_DEVICE shell monkey -p $app -c android.intent.category.LAUNCHER 1 &> /dev/null
