#!/bin/bash
sleep 1
if [ -z "$1" ] ; then
   adb pull /mnt/sdcard/output.mp4 ~/Desktop/video-$(date +%Y-%m-%d-%H-%M-%S).mp4
else
   adb pull /mnt/sdcard/output.mp4 ~/Desktop/$1.mp4
fi
adb shell rm /mnt/sdcard/output.mp4
