#!/bin/bash
#nice intro
echo
echo "Android APP stress test v1.2"
echo "---------------------------"

#get app package name
app=$(adb shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)

#check if display is on with suitable app
if ! ([[ $app == *"com"* ]] || [[ $app == *"cz"* ]]) ; then
   echo "No suitable app in foreground!";
   echo "Unlock your phone and open APP you want to test.";
   echo "Aborting...";
   echo
   exit
fi

#check/set number of input events
if [ -z "$1" ] || (( $1<1 )); then
   echo "Invalid number of input events in argument!";
   echo 'Use "adb_stresstest x" where x>0.';
   echo "Aborting...";
   echo
   exit
else
   events=$1
fi

#set seed
if ! [ -z "$2" ]; then
   echo "Seed set to: "$2;
   seed=$2
else
   seed=$RANDOM
   echo "Seed not specified!"
   echo 'Use "adb_stresstest x y" where y>0 to set seed.' 
   echo "Setting random seed: "$RANDOM;
fi

#checks passed
echo "Running stress test on: "$app
logname="$app-stresstest-`date +%Y-%m-%d-%H-%M-%S`.log"

#lock screen
task_id=$(adb shell dumpsys activity | grep mFocusedActivity | rev) #get focused activity info and reverse it
set $task_id #breaks task_id into $1 $2 ...
task_id=$1 #saves $1 into task_id
task_id=$(echo $task_id | rev) # reverse string back
task_id=${task_id//[!0-9]/} #strip non numeric chars from task_id
adb shell am task lock $task_id; #lock current app to prevent monkey escape
adb shell input tap 865 1620 #ugly hardcoded tap for my screen size, substitute them by (x,y) of your confirm button
echo "App locked to screen."

#run test
adb shell monkey -p $app -s $seed --pct-syskeys 0 --pct-anyevent 0 --monitor-native-crashes $events > ~/Desktop/$logname
echo "Seed: "$seed >> ~/Desktop/$logname

#unlock screen
adb shell am task lock stop
echo "App unlocked from screen."
echo "---------------------------"
echo "Test completed, log saved to desktop: "$logname

