#!/bin/bash
source ./adb_devices

choose_device

app=$(adb -s $selected shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)
adb -s $selected shell am force-stop $app
echo Relaunching $app
adb -s $selected shell monkey -p $app -c android.intent.category.LAUNCHER 1 &> /dev/null
