#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

echo "⚙️ Launching system settings app..."
adb -s $SELECTED_DEVICE shell am start -a android.settings.SETTINGS &> /dev/null
