#!/bin/bash

#nice intro
ver="1.2";
echo;
echo "Android APP stress test loop "$ver;
echo "---------------------------";

#get app package name
app=$(adb shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)
echo "Package name: "$app

#check if display is on with suitable app
if ! ([[ $app == *"com"* ]] || [[ $app == *"cz"* ]] || [[ $app == *"ticktackform"* ]]) ; then
   echo "No suitable app in foreground!";
   echo "Unlock your phone and open APP you want to test.";
   echo "Aborting...";
   echo
   exit
fi

#check/set number of loops
loops=0
if [ -z "$1" ] || (( $1<1 )); then
   while [ -z "$loops" ] || [ $loops -le 0 ]  ; do
      echo -n "Please specify number of tests: ";
      read loops;
   done
else
   echo "Test will run $1x.";
   loops=$1;
fi

#check/set number input events
events=0
if [ -z "$2" ] || (( $2<1 )); then
   while [ -z "$events" ] || [ $events -le 0 ]  ; do
      echo -n "Please specify number of input events: ";
      read events;
   done
else
   echo "Each test will include $2 input events.";
   events=$2;
fi

#run loop
for i in $(seq 1 $loops); do
   echo "Restarting $app"
   adb shell am force-stop $app >/dev/null 2>&1 #kill app to have fresh start
   adb shell monkey -p $app -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1  #start app
   #wait for $app to appear
   sec=0;
   until [ $(adb shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev) == $app ] ; do ((sec++)) ; echo -ne "Waiting for launch $sec seconds..." "\r" ; sleep 1 ; done 
   echo
   #blaze that
   echo "Running test number "$i
   bash adb_test $events
done

#show results 
echo "---------------------------";
echo $loops "tests finished!"
if [ $(ls ~/Desktop | grep .log | wc -l) -gt 0 ] ; then
   crashcount=$(ls ~/Desktop | grep CRASH | wc -l)
   killcount=$(ls ~/Desktop | grep KILLED | wc -l)
   freezecount=$(ls ~/Desktop | grep FREEZE | wc -l)
   if [ $crashcount -gt 0 ] ; then echo "App crashed: "$crashcount"x"; fi
   if [ $freezecount -gt 0 ] ; then echo "App freezed: "$freezecount"x"; fi
   if [ $killcount -gt 0 ] ; then echo "Monkey killed: "$killcount"x"; fi
   loops=$((loops - crashcount - freezecount - killcount))
   echo "App survived: "$loops"x"
   echo "Logs from failed tests are located at ~/Desktop"
   echo
else
   echo "App survived them all!" 
   echo  
fi
