#!/bin/bash
source ./adb_devices

choose_device

echo "Taking screenshot from $selected"
adb -s $selected shell screencap -p /mnt/sdcard/output.png
if [ -z "$1" ] ; then
  adb -s $selected pull /mnt/sdcard/output.png ~/Desktop/screenshot-$(date +%Y-%m-%d-%H-%M-%S).png
else
  adb -s $selected pull /mnt/sdcard/output.png ~/Desktop/$1.png
fi
adb -s $selected shell rm /mnt/sdcard/output.png
