#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
android_choose_device

BOUNDS_STATE=$(adb -s $SELECTED_DEVICE shell getprop debug.layout | tr -cd '[[:alnum:]]._-')
if [ $BOUNDS_STATE == "false" ] ; then
  echo "🔍 Turning layout bounds on..."
  adb -s $SELECTED_DEVICE shell setprop debug.layout true &> /dev/null
else
  echo "👋 Turning layout bounds off..."
  adb -s $SELECTED_DEVICE shell setprop debug.layout false &> /dev/null
fi

adb -s $SELECTED_DEVICE shell service check SurfaceFlinger &> /dev/null
adb -s $SELECTED_DEVICE shell service call activity 1599295570 &> /dev/null
