#!/bin/bash
location=$(dirname "$0")
source $location/device_chooser
choose_device

WEB=http://$1
echo "🌎 Opening $WEB in web browser..."
adb -s $SELECTED_DEVICE shell am start -a android.intent.action.VIEW -d "$WEB"
