#!/bin/bash

if [[ "$1" != "" ]]
then
    TEXT=$1
else
    read -s -p "Enter text you want to insert: " TEXT
fi

#GET device list
devices=()
for line in `adb devices | grep -v "List"  | awk '{print $1}'`
do
  device=`echo $line | awk '{print $1}'`
  devices+=("$device")
done

#If mutliple available
if [ ${#devices[@]} -gt 1 ]
then
   echo Multiple devices available: ${devices[@]}
   select opt in "${devices[@]}"
   do
     case $opt in
        *) selected=$opt;break; ;;
      esac
  done
else
   selected="${devices[0]}"
fi

if [ "$#" -gt 1 ]; 
then
    for var in "$@"
    do
        ESCAPED_TEXT=`echo $var | sed -e 's/ /\%s/g'`
        adb -s $selected shell input text "$ESCAPED_TEXT"
	sleep 0.5
	if ! [ $var = ${@:$#} ] #if not last argument, jump to next field
	then
	    adb -s $selected shell input keyevent 61
	fi
    done
else
    ESCAPED_TEXT=`echo $TEXT | sed -e 's/ /\%s/g'`
    adb -s $selected shell input text "$ESCAPED_TEXT"
fi


