#!/bin/bash

#GET device list
devices=()
for line in `adb devices | grep -v "List"  | awk '{print $1}'`
do
  device=`echo $line | awk '{print $1}'`
  devices+=("$device")
done

#If mutliple available
if [ ${#devices[@]} -gt 1 ]
then
   echo Multiple devices available: ${devices[@]}
   select opt in "${devices[@]}"
   do
     case $opt in
        *) selected=$opt;break; ;;
      esac
  done
else
   selected="${devices[0]}"
fi

app=$(adb -s $selected shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)

adb -s $selected shell am force-stop $app
echo Relaunching $app
adb -s $selected shell monkey -p $app -c android.intent.category.LAUNCHER 1 &> /dev/null