#!/bin/bash
trap 'ctrlc $@' 1 2 3 6 15

ctrlc()
{
sleep 1
if [ -z "$1" ] ; then
   adb -s $selected pull /mnt/sdcard/output.mp4 ~/Desktop/video-$(date +%Y-%m-%d-%H-%M-%S).mp4
else
   adb -s $selected pull /mnt/sdcard/output.mp4 ~/Desktop/$1.mp4
fi
adb -s $selected shell rm /mnt/sdcard/output.mp4
exit
}

#GET device list
devices=()
for line in `adb devices | grep -v "List"  | awk '{print $1}'`
do
  device=`echo $line | awk '{print $1}'`
  devices+=("$device")
done

#If mutliple available
if [ ${#devices[@]} -gt 1 ]
then
   echo Multiple devices available: ${devices[@]}
   select opt in "${devices[@]}"
   do
     case $opt in
        *) selected=$opt;break; ;;
      esac
  done
else
   selected="${devices[0]}"
fi

echo Starting recording on $selected, stop it with ctrl^c
adb -s $selected shell screenrecord --verbose /mnt/sdcard/output.mp4
