#!/bin/bash
source ./adb_devices

choose_device

app=$(adb -s $selected shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)

read -r -p "Are you sure, you want to remove the data of $app [y/n] " response
case "$response" in
    [yY])
        ;;
    *)
        exit
        ;;
esac

adb -s $selected shell pm clear $app
echo Relaunching $app
adb -s $selected shell monkey -p $app -c android.intent.category.LAUNCHER 1 &> /dev/null
