#!/bin/bash
location=$(dirname "$0")
source $location/device_chooser
choose_device

read -r -p "Are you sure, you want to remove ALL installed packages and delete the contents of /sdcard/Download on $selected? [y/n] " response
case "$response" in
    [yY])
        ;;
    *)
        exit
        ;;
esac

IFS=$'\n'
packages=($(adb -s $selected shell 'pm list packages -3 -f' | sed -e 's/.*=//' | sort))
unset IFS

for pkg in "${packages[@]}"
do

   if [[ $pkg = *"funtaster"* ]] || [[ $pkg = *"io.crash.air"* ]] || [[ $pkg = *"de.codenauts.hockeyapp"* ]] || [[ $pkg = *"chrome"* ]]; then
      echo "Skipping $pkg"
      continue
   fi

   pkg=${pkg%$'\r'} #removes trailing \r
   echo Uninstalling $pkg
   adb -s $selected shell "pm uninstall $pkg"

done

echo Clearing /sdcard/Download
adb -s $selected shell rm -r /sdcard/Download/*
