#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
trap 'ctrlc $@' 1 2 3 6 15

ctrlc()
{
sleep 1
if [ -z "$1" ] ; then
   FILENAME=$SELECTED_DEVICE_MODEL-API$SELECTED_DEVICE_SDK-$(date +%Y-%m-%d-%H-%M-%S)
else
   FILENAME=$1
fi
echo "📁 Copying the video from device..."
adb -s $SELECTED_DEVICE pull /mnt/sdcard/output.mp4 ~/Desktop/$FILENAME.mp4 &> /dev/null
adb -s $SELECTED_DEVICE shell rm /mnt/sdcard/output.mp4 &> /dev/null
exit
}

choose_device

echo "📹 Starting recording on $SELECTED_DEVICE, stop it with ctrl^c"
adb -s $SELECTED_DEVICE shell screenrecord /mnt/sdcard/output.mp4
