#!/bin/bash
source ./adb_devices

if [[ "$1" != "" ]]
then
    TEXT=$1
else
    read -s -p "Enter text you want to insert: " TEXT
fi

choose_device

if [ "$#" -gt 1 ];
then
    for var in "$@"
    do
        ESCAPED_TEXT=`echo $var | sed -e 's/ /\%s/g'`
        adb -s $selected shell input text "$ESCAPED_TEXT"
	sleep 0.5
	if ! [ $var = ${@:$#} ] #if not last argument, jump to next field
	then
	    adb -s $selected shell input keyevent 61
	fi
    done
else
    ESCAPED_TEXT=`echo $TEXT | sed -e 's/ /\%s/g'`
    adb -s $selected shell input text "$ESCAPED_TEXT"
fi
