#!/bin/bash
location=$(dirname "$0")
source $location/device_chooser
choose_device

adb -s $SELECTED_DEVICE shell monkey -p com.android.vending -c android.intent.category.LAUNCHER 1 &> /dev/null
adb -s $SELECTED_DEVICE shell input keyevent 84
adb_paste $1
