#!/bin/bash
if [ -z "$1" ] ; then
   adb pull /mnt/sdcard/output.mp4 ~/Desktop/output.mp4
   sys_togif ~/Desktop/output.mp4 360x640 ~/Desktop/gif-$(date +%Y-%m-%d-%H-%M-%S)
   rm ~/Desktop/output.mp4
else
   adb pull /mnt/sdcard/output.mp4 ~/Desktop/output.mp4
   sys_togif ~/Desktop/output.mp4 360x640 ~/Desktop/$1
   rm ~/Desktop/output.mp4
fi
adb shell rm /mnt/sdcard/output.mp4
