#!/bin/bash

#GET device list
devices=()
for line in `adb devices | grep -v "List"  | awk '{print $1}'`
do
  device=`echo $line | awk '{print $1}'`
  devices+=("$device")
done

#If mutliple available
if [ ${#devices[@]} -gt 1 ]
then
   echo Multiple devices available: ${devices[@]}
   select opt in "${devices[@]}"
   do
     case $opt in
        *) selected=$opt;break; ;;
      esac
  done
else
   selected="${devices[0]}"
fi

#get package name from .apk
aapt_path=$(find $ANDROID_HOME -name 'aapt' | sort | tail -1)
package_name=$($aapt_path dump badging $1 | grep package:\ name);
package_name=$(echo $package_name | sed 's/^[^'\'']*'\''//');
package_name=$(echo $package_name | sed 's/'\''.*//');

adb -s $selected install -r -d $1 
adb -s $selected shell monkey -p $package_name -c android.intent.category.LAUNCHER 1 &> /dev/null