#!/bin/bash
re='^[0-9]+$'

#GET device list
devices=()
for line in `adb devices | grep -v "List"  | awk '{print $1}'`
do
  device=`echo $line | awk '{print $1}'`
  devices+=("$device")
done

#If mutliple available
if [ ${#devices[@]} -gt 1 ]
then
   echo Multiple devices available: ${devices[@]}
   select opt in "${devices[@]}"
   do
     case $opt in
        *) selected=$opt;break; ;;
      esac
  done
else
   selected="${devices[0]}"
fi

if [ -z "$1" ]
then
   echo usage: greplog \<string\> \<lines\>
   echo string - type what are you looking for \(required\)
   echo lines - how many surrounding lines you want to print \(optional, default is 10\)
else
   if [ -z "$2" ]
   then
      adb -s $selected logcat | grep --colour -C 10 $1
   else
      if ! [[ $2 =~ $re ]]
      then
         echo error: second argument is not number
      else
         adb -s $selected logcat | grep --colour -C $2 $1
      fi
   fi
fi