#!/bin/bash
TOOLKIT_LOCATION=$(dirname "$0")
LOCAL_EMULATOR_LIST=$TOOLKIT_LOCATION/toolkit_emulator_list.txt

launch_emulator(){
  read -p "📝 Enter emulator number: " EMULATOR_INDEX
  EMULATOR_NAME=$(sed $EMULATOR_INDEX!d $LOCAL_EMULATOR_LIST)
  if [[ $EMULATOR_INDEX == "" || $EMULATOR_NAME == "" ]]; then
    echo -en "\033[1A\033[2K" #deletes last echoed line in terminal
    launch_emulator
  else
    echo  "🚀 Launching emulator..."
    nohup $ANDROID_HOME/tools/emulator -avd $EMULATOR_NAME -no-snapshot &> /dev/null &
  fi
}

echo "⏳ Getting Android emulator list..."
rm -f $LOCAL_EMULATOR_LIST
~/Library/Android/sdk/tools/bin/avdmanager list avd | grep Name | awk '{print $2}' >> $LOCAL_EMULATOR_LIST
echo "📱 Available emulators:"
cat $LOCAL_EMULATOR_LIST | nl
launch_emulator
