#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device


if [[ "$1" != "" ]];
then
    PACKAGE_NAME=$1
else
    PACKAGE_NAME=$(adb -s $SELECTED_DEVICE shell dumpsys window windows | grep mCurrentFocus | cut -d'/' -f1 | rev | cut -d' ' -f1 | rev)
fi

android_is_installed $PACKAGE_NAME

echo "🔪 Killing $PACKAGE_NAME"
adb -s $SELECTED_DEVICE shell am force-stop $PACKAGE_NAME
echo "🚀 Launching..."
adb -s $SELECTED_DEVICE shell monkey -p $PACKAGE_NAME -c android.intent.category.LAUNCHER 1 &> /dev/null
