#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

if [[ "$1" != "" ]]
then
    TEXT=$1
else
    read -p "📝 Enter text you want to insert: " TEXT
fi

if [ "$#" -gt 1 ];
then
    for var in "$@"
    do
        ESCAPED_TEXT=`echo "$var" | sed -e 's/ /\%s/g'`
        adb -s $SELECTED_DEVICE shell input text "$ESCAPED_TEXT"
	sleep 0.5
	if ! [ $var = ${@:$#} ] #if not last argument, jump to next field
	then
	    adb -s $SELECTED_DEVICE shell input keyevent 61
	fi
    done
else
    ESCAPED_TEXT=`echo $TEXT | sed -e 's/ /\%s/g'`
    adb -s $SELECTED_DEVICE shell input text "$ESCAPED_TEXT"
fi
