#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device



echo "🔆 Setting max brightness"
adb -s $SELECTED_DEVICE shell settings put system screen_brightness_mode 0
adb -s $SELECTED_DEVICE shell settings put system screen_brightness 255

echo "🌐 Checking network"
adb -s $SELECTED_DEVICE shell dumpsys netstats | grep -E 'iface=wlan.*networkId' | grep EDGE &> /dev/null
if [ $? -eq 0 ]
then
  echo "❗️ EDGE network is connected"
fi

echo "📆 Checking date"
LOCAL_DATE=$(date|cut -f1,2 -d':')
DEVICE_DATE=$(adb -s $SELECTED_DEVICE shell date|cut -f1,2 -d':')
if [ "$DEVICE_DATE" != "$LOCAL_DATE" ]
then
  echo "❗️ Date is set manually"
fi
