#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

WEB=http://$1
echo "🌎 Opening $WEB in web browser..."
adb -s $SELECTED_DEVICE shell am start -a android.intent.action.VIEW -d "$WEB"
