#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
android_choose_device

WEB=$1

case $1 in
  'http://'*)
    ;;
  'https://'*)
    ;;
  *'://'*)
    ;;
  *)
    WEB='http://'$WEB
    ;;
esac

echo "🌎 Opening $WEB in web browser..."
adb -s $SELECTED_DEVICE shell am start -a android.intent.action.VIEW -d "$WEB" &> /dev/null
