#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/common_tools
ios_choose_device

if [ -z "$1" ] ; then
  DIRNAME=CRASH_LOGS_$SELECTED_DEVICE_MODEL-iOS$SELECTED_DEVICE_VERSION-$(date +%Y-%m-%d-%H-%M-%S)
else
  DIRNAME=$1
fi

cd ~/Desktop
mkdir $DIRNAME
echo "📁 Copying crash logs from the device..."
idevicecrashreport -k -u $SELECTED_DEVICE $DIRNAME &> /dev/null

echo "🔥 Cleaning up..."
cd $DIRNAME
rm -R -- */ #remove unnecessary system logs
find . -type f ! -name '*.ips' -delete #remove non-crash logs

for file in *.ips; do
    mv "$file" "$(basename "$file" .ips).crash"
done

if [ -z "$(ls -A)" ]; then
   cd ..
   rm -rf $DIRNAME
   echo "❌ Nothing useful found!"
else
   echo "✅ Crash logs gathered to $DIRNAME"
fi
