#!/bin/bash
location=$(dirname "$0")
source $location/common_tools

if [ -z "$1" ] ; then
  echo "🤷‍ What should I install?"
  exit
fi

echo "⌛️ Installing..."
ideviceinstaller -i "$1" &> /dev/null
echo "✅ Done!"
