#!/bin/bash
location=$(dirname "$0")
source $location/common_tools

cd ~/Desktop
if [ -z "$1" ] ; then
  FILENAME=screenshot-$(date +%Y-%m-%d-%H-%M-%S)
else
  FILENAME=$1
fi

check_developer_image

echo "Screenshot saved into $FILENAME.png"
idevicescreenshot $FILENAME.png &> /dev/null
