#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
trap 'ctrlc $@' 1 2 3 6 15

ctrlc()
{
echo "Composing footage..."
cd ~/Desktop/$DIRNAME
 if [ -z "$1" ] ; then
   FILENAME=video-$(date +%Y-%m-%d-%H-%M-%S)
 else
   FILENAME=$1
fi
ffmpeg -r 10 -f image2 -loglevel quiet -i %d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p ../$FILENAME.mp4
cd ..
echo "Cleaning up..."
rm -rf $DIRNAME
exit
}

DIRNAME=iOS-recording-$(date +%Y-%m-%d-%H-%M-%S)

cd ~/Desktop
mkdir $DIRNAME
cd $DIRNAME

check_developer_image

echo "Recording screen..."
N=1;
while :; do
    idevicescreenshot $N.png >/dev/null 2>&1
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
      echo "🤷 Recording failed, error code: $EXIT_CODE"
      cd ..
      rm -rf $DIRNAME
      exit
    fi
    N=$(($N+1));
done
