#!/bin/bash
location=$(dirname "$0")
source $location/common_tools
ios_check_developer_image

cd ~/Desktop
if [ -z "$1" ] ; then
  ios_get_device_info
  FILENAME=$SELECTED_DEVICE_MODEL-iOS$SELECTED_DEVICE_VERSION-$(date +%Y-%m-%d-%H-%M-%S)
else
  FILENAME=$1
fi

idevicescreenshot $FILENAME.png &> /dev/null
EXIT_CODE=$?
if [ $EXIT_CODE -eq 0 ]; then
  echo "📸 Screenshot saved into $FILENAME.png"
else
  echo "🤷 Screenshot failed, error code: $EXIT_CODE"
fi
