#!/bin/bash
location=$(dirname "$0")
source $location/common_tools

cd ~/Desktop
if [ -z "$1" ] ; then
  FILENAME=screenshot-$(date +%Y-%m-%d-%H-%M-%S)
else
  FILENAME=$1
fi

check_developer_image

idevicescreenshot $FILENAME.png &> /dev/null
EXIT_CODE=$?
if [ $EXIT_CODE -eq 0 ]; then
  echo "Screenshot saved into $FILENAME.png"
else
  echo "🤷 Screenshot failed, error code: $EXIT_CODE"
fi
