#!/bin/bash
TOOLKIT_LOCATION=$(dirname "$0")
source $TOOLKIT_LOCATION/common_tools

help(){
  echo -e "❌ Use one of the following options:\n  launch - choose and launch simulator\n  web <url> - open link in web browser"
}

launch_simulator(){
  echo "⏳ Getting installed iOS simulator list..."
  rm -f $LOCAL_SIMULATOR_LIST
  xcrun simctl list | grep -i "shutdown\|booted\|-- iOS\|-- tvOS\|-- watchOS" | grep -v "unavailable\|Watch:\|Phone:" | sed 's/ (Shutdown) //g' | sed 's/ (Booted) //g' >> $LOCAL_SIMULATOR_LIST

  echo "📱 Available simulators:"
  cat $LOCAL_SIMULATOR_LIST | nl
  read -p "📝 Enter simulator number: " SIMULATOR_INDEX

  SIMULATOR_ID=$(sed $SIMULATOR_INDEX!d $LOCAL_SIMULATOR_LIST)
  check_simulator_choice
  echo  "🚀 Launching simulator..."
  xcrun simctl boot $SIMULATOR_ID
  open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/
}

open_web(){
  check_web_url $1
  echo $SIMULATOR_ID
  echo $WEB_URL
  echo "🌎 Opening link in a web browser..."
  xcrun simctl openurl $SIMULATOR_ID $WEB_URL
}

case $1 in
  'launch')
    launch_simulator
    ;;
  'web')
    choose_running_simulator
    open_web $2
    ;;
   *)
    help
    ;;
esac
