#!/bin/bash
TOOLKIT_LOCATION=$(dirname "$0")
source $TOOLKIT_LOCATION/common_tools

LOCAL_SIMULATOR_LIST=$TOOLKIT_LOCATION/toolkit_simulator_list.txt

help(){
  if [[ $1 != "" ]]; then
    echo "🤷‍ Unknown option: $1"
  else
    echo "🤷 Argument missing."
  fi
  echo -e "Use one of the following options:\n  start - choose and launch a simulator\n  paste <text> - insert text into pasteboard\n  web <url> - open link in web browser"
}

choose_simulator(){
  read -p "📝 Enter simulator number: " SIMULATOR_INDEX
  SIMULATOR_ID=$(sed $SIMULATOR_INDEX!d $LOCAL_SIMULATOR_LIST)

  if [[ $SIMULATOR_INDEX == "" || $SIMULATOR_ID != *"("* ]]; then
    echo -en "\033[1A\033[2K" #deletes last echoed line in terminal
    choose_simulator
  fi
  SIMULATOR_ID=$(echo $SIMULATOR_ID | sed 's/.*(\(.*\))/\1/')
}

choose_running_simulator(){
  xcrun simctl list -v devices | grep -i booted | sed 's/ (Booted) //g' > $LOCAL_SIMULATOR_LIST
  RUNNING_SIMULATOR_COUNT=$(wc -l < toolkit_simulator_list.txt)

  if [[ $RUNNING_SIMULATOR_COUNT -le 0 ]]; then
    echo "❌ No running simulators..."
    exit
  elif [[ $RUNNING_SIMULATOR_COUNT -eq 1 ]]; then
    SIMULATOR_ID=$(sed 1!d $LOCAL_SIMULATOR_LIST | sed 's/.*(\(.*\))/\1/')
    return
  fi

  echo "📱 Available simulators:"
  cat $LOCAL_SIMULATOR_LIST | nl
  choose_simulator
}

start_simulator(){
  echo "⏳ Getting installed iOS simulator list..."
  rm -f $LOCAL_SIMULATOR_LIST
  xcrun simctl list | grep -i "shutdown\|booted\|-- iOS\|-- tvOS\|-- watchOS" | grep -v "unavailable\|Watch:\|Phone:" | sed 's/ (Shutdown) //g' | sed 's/ (Booted) //g' >> $LOCAL_SIMULATOR_LIST

  echo "📱 Installed simulators:"
  cat $LOCAL_SIMULATOR_LIST | nl
  choose_simulator
  echo  "🚀 Launching simulator..."
  xcrun simctl boot $SIMULATOR_ID
  open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/
}

open_web(){
  check_web_url $1
  echo "🌎 Opening link in a web browser..."
  xcrun simctl openurl $SIMULATOR_ID $WEB_URL
}

launch_app(){
  if [[ $1 == "" || $1 != "com."*"."* ]]; then
    read -p "📝 Enter bundle id: " BUNDLE_ID
    launch_app "$BUNDLE_ID"
  else
    echo "🚀 Launching the app..."
    xcrun simctl launch $SIMULATOR_ID $1
  fi
}

insert_clipboard(){
  if [[ $1 == "" ]]; then
    read -p "📝 Enter pasteboard text: " TEXT
    insert_clipboard "$TEXT"
  else
    echo "📥 Inserting text into clipboard..."
    echo $1 | xcrun simctl pbcopy $SIMULATOR_ID
  fi
}

case $1 in
  'start')
    start_simulator $2
    ;;
  'web')
    choose_running_simulator
    open_web $2
    ;;
  'launch')
    choose_running_simulator
    launch_app $2
    ;;
  'paste')
    choose_running_simulator
    insert_clipboard "$2"
    ;;
   *)
    help $1
    ;;
esac
