#!/bin/bash
TOOLKIT_LOCATION=$(dirname "$0")
source $TOOLKIT_LOCATION/common_tools

choose_running_simulator


check_web_url $1
echo $SIMULATOR_ID
echo $WEB_URL
echo "🌎 Opening link in a web browser..."
xcrun simctl openurl $SIMULATOR_ID $WEB_URL
