#!/bin/bash
echo "
network diagnostics - traceroute,mtr
system diagnostics - free 

"
#show me the funny
separator="-----------------------------------------------------------------------------------"
uptime
echo $separator
echo " memory stats"
echo $separator
free -h

