#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
trap 'ctrlc $@' 1 2 3 6 15
CHANGED=0

ctrlc()
{
  if [ $CHANGED -eq 1 ]; then
    restore_animation_speed
  fi
  exit
}

set_animation_speed(){
  CHANGED=1
  adb -s $SELECTED_DEVICE shell settings put global animator_duration_scale $1
  adb -s $SELECTED_DEVICE shell settings put global transition_animation_scale $1
  adb -s $SELECTED_DEVICE shell settings put global window_animation_scale $1
}

restore_animation_speed(){
  echo "🔄 Restoring animation speed to default..."
  set_animation_speed 1
}

android_choose_device

if ! [ -z $1 ]; then
  set_animation_speed $1
  read -p "⚡️ Animation scale set to $1 (bigger is slower), hit ENTER to stop"
else
  echo -n "🐌 Slowing down animation speed..."
  set_animation_speed 5
  read -n 1 -p ", press ENTER to stop"
fi

restore_animation_speed
