#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

BOUNDS_STATE=$(adb -s $SELECTED_DEVICE shell getprop debug.layout | tr -cd '[[:alnum:]]._-')
if [ -z "$BOUNDS_STATE" ] || [ "$BOUNDS_STATE" == "false" ]; then
  echo "📐 Turning layout bounds on..."
  adb -s $SELECTED_DEVICE shell setprop debug.layout true &> /dev/null
else
  echo "👋 Turning layout bounds off..."
  adb -s $SELECTED_DEVICE shell setprop debug.layout false &> /dev/null
fi

# force screen redraw
adb -s $SELECTED_DEVICE shell service check SurfaceFlinger &> /dev/null
adb -s $SELECTED_DEVICE shell service call activity 1599295570 &> /dev/null
