#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools

list_build_variants(){
  echo "⏳ Detecting build variant list..."
  if [ -n "$1" ];
  then
    cd $PWD/$1 &> /dev/null
    if [ $? != "0" ];
    then
      echo "🤷‍ Location does not exist"
      exit
    fi
  fi

  if ! [ -f "gradlew" ];
  then
    echo "🤷‍ Android project not found"
    exit
  fi

  TASK_LIST="toolkit_task_list.txt"
  ./gradlew tasks | grep '^install' > $TASK_LIST

  if [ "$(cat $TASK_LIST | wc -l)" -eq 0 ]; then
    echo "🤷‍ No Android project build variants available"
    exit
  else
    echo "🔨 Available:"
    cat $TASK_LIST | nl
  fi
}

build_project_variant(){
  read -p "📝 Choose build variant: " VARIANT_INDEX
  TASK=$(sed $VARIANT_INDEX!d $TASK_LIST | awk '{ print $1 }' )
  if [[ $VARIANT_INDEX == "" || $TASK == "" ]]; then
    delete_lastline
    build_project_variant
  else
    echo  "🚀 Triggering new build..."
    ANDROID_SERIAL=$SELECTED_DEVICE ./gradlew $TASK
  fi
  if [ $? == "0" ];
  then
    VARIANT=${TASK#"install"}
    echo  "✅ $VARIANT build variant successfully installed"
  else
    echo  "❌ $VARIANT build variant installation failed"
  fi
}

OLD_PWD="$PWD"
android_choose_device
list_build_variants "$@"
build_project_variant
rm $TASK_LIST
cd $OLD_PWD
