#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
LOCAL_EMULATOR_LIST=$LOCATION/../data/toolkit_emulator_list.txt

help(){
  if [[ $1 != "" ]]; then
    echo "🤷‍ Unknown option: $1"
  else
    echo "🤷 Argument missing"
  fi
  echo -e "Use one of the following options:\n  start - choose and launch installed emulator\n  call <number> - trigger fake call\n  sms <number> <text> - recieve fake sms\n  gps <lat> <long> - set manual gps location"
}

get_emulator_list(){
  echo "⏳ Getting Android emulator list..."
  rm -f $LOCAL_EMULATOR_LIST
  ~/Library/Android/sdk/tools/bin/avdmanager list avd | grep Name | awk '{print $2}' >> $LOCAL_EMULATOR_LIST
  if [ "$(cat $LOCAL_EMULATOR_LIST | wc -l)" -eq 0 ]; then
    should_proceed "🤷‍ No emulators installed, install via Android Studio?"
    echo "⏳ Opening Android Studio..."
    open -a /Applications/Android\ Studio.app
    exit
  else
    echo "📱 Available:"
    cat $LOCAL_EMULATOR_LIST | nl
  fi
}

launch_emulator(){
  if [ -z "$1" ]; then
    read -p "📝 Choose: " EMULATOR_INDEX
  else
    EMULATOR_INDEX=$1
  fi
  EMULATOR_NAME=$(sed $EMULATOR_INDEX!d $LOCAL_EMULATOR_LIST)
  if [[ $EMULATOR_INDEX == "" || $EMULATOR_NAME == "" ]]; then
    delete_lastline
    launch_emulator
  else
    echo  "🚀 Launching emulator..."
    nohup $ANDROID_HOME/tools/emulator -avd $EMULATOR_NAME -no-snapshot &> /dev/null &
    rm $LOCAL_EMULATOR_LIST
  fi
}

call(){
  if [ -z "$1" ];then
    read -p "📝 Insert caller number: " NUMBER
  else
    NUMBER=$1
  fi
  echo "📞 Making a call..."
  android_telnet_command "gsm call $NUMBER"
  echo "✅ Done"
}

send_sms(){
  if [ -z "$1" ];then
    read -p "📝 Insert sender number: " NUMBER
  else
    NUMBER=$1
  fi

  if [ -z "$2" ];then
    read -p "📝 Insert text: " TEXT
  else
    TEXT=$2
  fi

  echo "📝 Sending fake SMS..."
  android_telnet_command "sms send $NUMBER $TEXT"
  echo "✅ Done"
}

set_gps(){
  if [ -z "$1" ];then
    read -p "📝 Insert latitude: " LAT
  else
    LAT=$1
  fi

  if [ -z "$2" ];then
    read -p "📝 Insert longtitude: " LONG
  else
    LONG=$2
  fi

  echo "🌎 Setting manual GPS location..."
  android_telnet_command "geo fix $LONG $LAT"
  echo "✅ Done"
}

check_for_update

case $1 in
  'start')
    get_emulator_list
    launch_emulator "$2"
    ;;
  'call')
    call "$2"
    ;;
  'sms')
    send_sms "$2" "$3"
    ;;
  'gps')
    set_gps "$2" "$3"
    ;;
   *)
    help "$1"
    ;;
esac
