#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
LOCAL_EMULATOR_LIST=$LOCATION/../data/toolkit_emulator_list.txt

get_emulator_list(){
  echo "⏳ Getting Android emulator list..."
  rm -f $LOCAL_EMULATOR_LIST
  ~/Library/Android/sdk/tools/bin/avdmanager list avd | grep Name | awk '{print $2}' >> $LOCAL_EMULATOR_LIST
  if [ "$(cat $LOCAL_EMULATOR_LIST | wc -l)" -eq 0 ]; then
    echo "🤷‍ No emulators available."
    exit
  else
    echo "📱 Available:"
    cat $LOCAL_EMULATOR_LIST | nl
  fi
}

launch_emulator(){
  read -p "📝 Choose: " EMULATOR_INDEX
  EMULATOR_NAME=$(sed $EMULATOR_INDEX!d $LOCAL_EMULATOR_LIST)
  if [[ $EMULATOR_INDEX == "" || $EMULATOR_NAME == "" ]]; then
    delete_lastline
    launch_emulator
  else
    echo  "🚀 Launching emulator..."
    nohup $ANDROID_HOME/tools/emulator -avd $EMULATOR_NAME -no-snapshot &> /dev/null &
    rm $LOCAL_EMULATOR_LIST
  fi
}

check_for_update
get_emulator_list
launch_emulator
