#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

help(){
  echo "Usage: afakecall <phone_number>"
}

call(){
  echo "📞 Making a call..."
  android_telnet_command "gsm call $1"
  echo "✅ Done"
}

if [ -n "$1" ]; then
    call "$1"
else
    help
fi
