#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools

help(){
  echo "Usage: afakegps <latitude> <longtitude>"
}


set_gps(){
  echo "🌎 Setting manual GPS location..."
  android_telnet_command "geo fix $2 $1"
  echo "✅ Done"
}

if [ -n "$2" ]; then
    set_gps "$1" "$2"
else
    help
fi
