#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

help(){
  echo "Usage: afakegps <latitude> <longtitude>"
}


set_gps(){
  echo "🌎 Doing stuff..."
  TOKEN=$(cat $HOME/.emulator_console_auth_token)
  { echo "o localhost 5554"; sleep 1; echo "auth $TOKEN"; sleep 1; echo "geo fix $2 $1"; } | telnet
  echo "🗺 Fake gps location set"
}

if [ -n "$2" ]; then
    set_gps "$1" "$2"
else
    help
fi
