#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

help(){
  echo "Usage: afakesms <phone_number> <sms_text>"
}


send_sms(){
  echo "📝 Sending fake SMS..."
  android_telnet_command "sms send $1 $2"
  echo "✅ Done"
}

if [ -n "$2" ]; then
    send_sms "$1" "$2"
else
    help
fi
