#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

help(){
  echo "Usage: afakecall <phone_number>"
}


call(){
  echo "📞 Making a call..."
  TOKEN=$(cat $HOME/.emulator_console_auth_token)
  { echo "o localhost 5554"; sleep 1; echo "auth $TOKEN"; sleep 1; echo "gsm call $1"; } | telnet
  echo "✅ Done"
}

if [ -n "$1" ]; then
    call "$1"
else
    help
fi
