#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
trap 'ctrlc $@' 1 2 3 6 15

ctrlc()
{
  restore_font_scale
  exit
}

set_font_scale(){
  PREVIOUS_SCALE=$(adb -s $SELECTED_DEVICE shell settings get system font_scale)
  adb -s $SELECTED_DEVICE shell settings put system font_scale $1
}

restore_font_scale(){
  set_font_scale $PREVIOUS_SCALE
  echo "🔄 Font scale restored to previous"
}

android_choose_device

if ! [ -z $1 ]; then
  echo -n "🔠 Setting font scale to $1..."
  set_font_scale $1
else
  echo -n "🔍 Setting font scale to 1.3..."
  set_font_scale 1.3
fi

if [ "$2" != "-k" ];then
  read -n 1 -p ", press ENTER to revert"
  restore_font_scale
fi
