#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
trap 'ctrlc $@' 1 2 3 6 15

ctrlc()
{
  restore_font_scale
  exit
}

set_font_scale(){
  echo -n "🔍 Setting font scale to $1..."
  PREVIOUS_SCALE=$(adb -s $SELECTED_DEVICE shell settings get system font_scale)
  adb -s $SELECTED_DEVICE shell settings put system font_scale $1
}

restore_font_scale(){
  set_font_scale $PREVIOUS_SCALE
  echo
  echo "🔄 Font scale restored to previous"
}

android_choose_device
if [ "$1" -eq "$1" ] 2> /dev/null
then
  set_font_scale $1
else
  set_font_scale 1.3
fi

if [ "$1" != "-k" ] && [ "$2" != "-k" ];then
  read -n 1 -p ", press ENTER to revert"
  restore_font_scale
fi
