#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools

abort(){
  echo $1
  exit
}

install_app(){
  echo "⌛️ Installing \"$PACKAGE_NAME\" to $1"
  adb -s $1 install -r "$2" &> /dev/null
  echo "🚀 Launching $APP_NAME..."
  adb -s $1 shell monkey -p $PACKAGE_NAME -c android.intent.category.LAUNCHER 1 &> /dev/null
}

check_args_valid(){
  if [[ "$1" != "-a" ]]; then
    FILE=$1
  else
    FILE=$2
  fi

  if [ ! -f "$PWD/$FILE" ] && [ ! -f "$FILE" ]; then
      abort "🤷‍ Installation file not found!"
  fi

  if [[ "$FILE" != *".apk" ]]; then
      abort "🤷 Unsupported file!"
  fi
}

run()
{
  if [[ $1 == "-a" ]]; then
    detect_package_info $2
    for line in `adb devices | grep -v "List"  | awk '{print $1}'`
    do
      DEVICE=`echo $line | awk '{print $1}'`
      install_app $DEVICE $2 &
    done
    wait
  else
    android_choose_device
    detect_package_info $1
    install_app $SELECTED_DEVICE $1
  fi
}

# "$@" - pass all arguments
check_args_valid "$@"
run "$@"
