#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

if [[ "$1" != "" && "$1" != "-s" ]]
then
    package=$1
else
    IFS=$'\n'
    if [[ "$1" == "-s" ]]; then
      ps=($(adb -s $SELECTED_DEVICE shell 'pm list packages -f' | sed -e 's/.*=//' | sort))
    else
      ps=($(adb -s $SELECTED_DEVICE shell 'pm list packages -3 -f' | sed -e 's/.*=//' | sort))
    fi
    unset IFS

    packages=()
    for p in "${ps[@]}" #removes trailing \r
    do
      p=${p%$'\r'}
      packages+=($p)
    done

    if [ ${#packages[@]} -eq 0 ]; then
        echo "🤷‍ No third-party apps installed, use alaunch -s to list system packages"
        exit
    fi

    echo "📋 Choose package to launch:"
    select opt in "${packages[@]}"
    do
     case $opt in
        *) package=$opt;break; ;;
      esac
    done
fi

echo "🚀 Launching $package..."
adb -s $SELECTED_DEVICE shell monkey -p $package -c android.intent.category.LAUNCHER 1 &> /dev/null
