#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
android_choose_device

filter_by_package(){
  android_is_package_installed "$1"
  echo "🔍 Filtering by package name: $1"
  PID=$(adb -s "$SELECTED_DEVICE" shell ps | grep -i "$1" | cut -c10-15)
  adb -s "$SELECTED_DEVICE" logcat | grep "$PID"
}

raw_log(){
  echo "📜 Device log:"
  adb -s "$SELECTED_DEVICE" logcat
}

if [ "$1" == "-f" ]; then
  if [ -z "$2" ]; then
    read -r -p "🔬 Insert package name (Android 7+) or leave empty to proceed: " PACKAGE
  else
    PACKAGE=$2
  fi
  filter_by_package "$PACKAGE"
else
    raw_log
fi
