#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
android_choose_device

tput setaf 1
should_proceed "🚫 REVOKE ALL GRANTED PERMISSIONS on $SELECTED_DEVICE?"
tput setaf 0
adb -s "$SELECTED_DEVICE" shell pm reset-permissions
