#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

screenshot_all(){
  for line in `adb devices | grep -v "List"  | awk '{print $1}'`
  do
    device=`echo $line | awk '{print $1}'`
    echo "📸 Taking screenshot from $device"
    adb -s $device shell screencap -p /mnt/sdcard/output.png
    adb -s $device pull /mnt/sdcard/output.png ~/Desktop/screenshot-$device-$(date +%Y-%m-%d-%H-%M-%S).png &> /dev/null
    adb -s $device shell rm /mnt/sdcard/output.png
  done
}

if [ "$1" == "-a" ];
then
  screenshot_all
else
  if [ -z "$1" ];
  then
    FILENAME=$SELECTED_DEVICE_MODEL-API$SELECTED_DEVICE_SDK-$(date +%Y-%m-%d-%H-%M-%S)
  else
    FILENAME=$1
  fi
  adb -s $SELECTED_DEVICE shell screencap -p /mnt/sdcard/output.png
  adb -s $SELECTED_DEVICE pull /mnt/sdcard/output.png ~/Desktop/$FILENAME.png &> /dev/null
  adb -s $SELECTED_DEVICE shell rm /mnt/sdcard/output.png
  echo "📸 Screenshot saved into $FILENAME.png"
fi
