#!/bin/bash
source "$LOCATION"/../common_tools
LOCATION=$(dirname "$0")
trap "kill 0" SIGINT # Kill all spawned subprocesses on ctrl^c

android_choose_device

adb -s "$SELECTED_DEVICE" shell ps | awk '/com\.android\.commands\.monkey/ { system("adb shell kill " $2) }' >/dev/null 2>&1
echo "🙈 Monkey eliminated, device is safe to use again"
