#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

UNINSTALL_COUNT=0
IGNORED_PACKAGES=( "com.thefuntasty.funtaster" "io.crash.air" "de.codenauts.hockeyapp" "ar.core" "com.framerjs.android" "com.figma.mirror" "com.invisionapp.ifa")
PACKAGES=($(adb -s $SELECTED_DEVICE shell pm list packages -f -3 | sed -e 's/.*=//' | sort))

if [[  "$1" == "-a" ]]; then
  should_proceed "💣 Delete all third party apps on $SELECTED_DEVICE_MODEL - $SELECTED_DEVICE?"
  for PKG in "${PACKAGES[@]}"
  do
    PKG=${PKG%$'\r'} #removes trailing \r
    echo $IGNORED_PACKAGES | grep "$PKG" &> /dev/null && { echo "⏩ Skipped $PKG"; continue; }
    echo "🔥 Uninstalling $PKG"
    adb -s $SELECTED_DEVICE shell "pm uninstall $PKG" &> /dev/null
    ((++UNINSTALL_COUNT))
  done
  echo "✅ Apps uninstalled: $UNINSTALL_COUNT"
  exit
elif [[ -n "$1" ]]; then
  PACKAGE=$1
  echo $PACKAGES | grep -w "$PACKAGE" &> /dev/null || { echo "🤷‍ Package \"$PACKAGE\" not installed"; exit; }
  echo $IGNORED_PACKAGES | grep -w "$PACKAGE" &> /dev/null && { echo "❌ Package \"$PACKAGE\" is whitelisted"; exit; }
fi

if [ -z "$PACKAGE" ]; then
  PACKAGES_LISTED=()
  for PKG in "${PACKAGES[@]}" #removes trailing \r
  do
    PKG=${PKG%$'\r'}
    echo "${IGNORED_PACKAGES[@]}" | grep "$PKG" &> /dev/null && { echo "⏩ Skipped $PKG"; continue; }
    PACKAGES_LISTED+=($PKG)
  done

  if [ ${#PACKAGES_LISTED[@]} -eq 0 ]; then
      echo "🤷‍ Nothing to uninstall"
      exit
  fi

  echo "📋 Choose package number:"
  select OPTION in "${PACKAGES_LISTED[@]}"
  do
   case $OPTION in
      *) PACKAGE=$OPTION;break; ;;
    esac
  done
fi

echo "🔥 Uninstalling $PACKAGE"
adb -s $SELECTED_DEVICE shell pm uninstall $PACKAGE &> /dev/null
