#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
android_choose_device

check_url "$1"
echo "🌎 Opening url..."
adb -s "$SELECTED_DEVICE" shell am start -a android.intent.action.VIEW -d "$URL" &> /dev/null
