#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
android_choose_device

tput setaf 1
should_proceed "💣 Wipe internal storage on $SELECTED_DEVICE_MODEL - $SELECTED_DEVICE?"
tput sgr0

echo "🔥 Deleting all data..."
adb -s $SELECTED_DEVICE shell rm -rf mnt/sdcard/*
echo "✅ Done"
