#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools

get_device_ip(){
  android_choose_device
  DEVICE_IP=$(adb -s $SELECTED_DEVICE shell ip route | awk '{print $9}')
}

setup_network_connection(){
  echo "🌎 Connecting the device via local network..."
  adb -s $SELECTED_DEVICE tcpip 5555 &> /dev/null
  echo "🌎 Getting device IP..."
  delete_lastline
  echo "🌎 Device IP: $DEVICE_IP"
  echo "🌎 Connecting..."
  STATUS=$(adb connect "$DEVICE_IP:5555")

  echo $STATUS | grep "refused" && echo "❌ Connection refused - already connected?" && return
  echo "✅ Connected successfully, you can unplug the USB cable"
}

setup_usb_connection(){
  echo "🔌 Connecting the device via USB..."
  adb disconnect "$DEVICE_IP:5555" &> /dev/null
  adb usb &> /dev/null
}

choose_connection(){
  echo "📝 Available connections:"
  echo -e "w) 🌎 WIFI\nu) 🔌 USB"
  read -r -n 1 -p "Select variant [w/u] " RESPONSE
  case "$RESPONSE" in
    [wW])
        ;;
    [uU])
        ;;
    *)
      echo
      echo "🤷‍ Invalid option."
      choose_connection $1
      ;;
  esac
  echo

  if [[ "$RESPONSE" == "w" ||  "$RESPONSE" == "W" ]]; then
    setup_network_connection
  else
    setup_usb_connection
  fi
}

get_device_ip
choose_connection
