#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
ios_choose_device
ios_device_info "$SELECTED_DEVICE"

GSM_URL='https://www.gsmarena.com/res.php3?sSearch='

MANUFACTURER=Apple
INFO=$(printf "%s %s - iOS %s" "$MANUFACTURER" "$MODEL" "$VERSION")

PHONE_URL=$GSM_URL$MODEL

echo "📱 $INFO - ID: $SELECTED_DEVICE"

should_proceed "🌐 Search for the device on GSMArena?"
open "$PHONE_URL"
