#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
ios_choose_device

if [ -z "$1" ] ; then
  DIRNAME=CRASH_LOGS_$SELECTED_DEVICE_MODEL-iOS$SELECTED_DEVICE_VERSION-$(date +%Y-%m-%d-%H-%M-%S)
else
  DIRNAME=$1
fi

cd ~/Desktop
mkdir $DIRNAME
yes_or_no "🔥 Delete the logs from the device afterwards?"
if [[ "$RESPONSE" == "y" ||  "$RESPONSE" == "Y" ]]; then
  echo "⏳ Moving crash logs to \"$DIRNAME\", this may take a while..."
  idevicecrashreport -u $SELECTED_DEVICE $DIRNAME &> /dev/null
else
  echo "📂 Copying crash logs to \"$DIRNAME\", this may take a while..."
  idevicecrashreport -k -u $SELECTED_DEVICE $DIRNAME &> /dev/null
fi

echo "🔥 Cleaning up..."
cd $DIRNAME
rm -R -- */ #remove unnecessary system logs
find . -type f ! -name '*.ips' -delete #remove non-crash logs

for file in *.ips; do
    mv "$file" "$(basename "$file" .ips).crash"
done

if [ -z "$(ls -A)" ]; then
   cd ..
   rm -rf $DIRNAME
   echo "❌ No useful logs found!"
else
   echo "✅ Crash logs saved to $DIRNAME"
fi
