#!/bin/bash
# shellcheck disable=SC2015

LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools

install_app(){
  echo "⌛️ Installing \"$2\" to $1..."
  ideviceinstaller -u "$1" -i "$2" &> /dev/null && "✅ Successfully installed to $1" || { echo "❌ Installation failed, try uinstalling the existing version or troubleshooting the package!"; exit 1; }
}

check_args_valid(){
  if [[ "$1" != "-a" ]]; then
    FILE=$1
  else
    FILE=$2
  fi

  if [ ! -f "$PWD/$FILE" ] && [ ! -f "$FILE" ]; then
      abort "🤷 Installation file not found!"
  fi

  if [[ "$FILE" != *".ipa" ]]; then
      abort "🤷 Unsupported file!"
  fi
}

run(){
  if [[ $1 == "-a" ]]; then
    ios_get_devices
    for ID in "${IOS_USB_DEVICES[@]}"
     do
      install_app "$ID" "$2" &
    done
    wait
  else
    ios_choose_device
    install_app "$SELECTED_DEVICE" "$1"
  fi
}

check_dependency "ideviceinstaller"
check_args_valid "$@"
run "$@"
