#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
ios_choose_device

RELAUNCH=true
INCLUDE_SYSTEM=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n)
      RELAUNCH=false
      ;;
    -s)
      INCLUDE_SYSTEM=true
      ;;
    -* )
      echo "❓ Unknown flag: $1"
      exit 1
      ;;
    * )
      PACKAGE="$1"
      ios_is_package_installed "$PACKAGE"
      ;;
  esac
  shift
done

if [[ -z "$PACKAGE" ]]; then
  if [[ "$INCLUDE_SYSTEM" == true ]]; then
    PACKAGES=($(go-ios apps --udid="$SELECTED_DEVICE" --system | jq -r '.[] | .CFBundleIdentifier'))
  else
    PACKAGES=($(go-ios apps --udid="$SELECTED_DEVICE" | jq -r '.[] | .CFBundleIdentifier'))
  fi

  PACKAGES_LISTED=()
  for P in "${PACKAGES[@]}" #removes trailing \r
  do
    P=${P%$'\r'}
    PACKAGES_LISTED+=("$P")
  done

  if [ ${#PACKAGES_LISTED[@]} -eq 0 ]; then
      echo "🤷‍ No third-party apps installed, use \"ikill -s\" to list system packages"
      exit 1
  fi

  echo "📋 Choose application to kill:"
  select OPTION in "${PACKAGES_LISTED[@]}"
  do
   case $OPTION in
      *) PACKAGE=$OPTION;break; ;;
    esac
  done
fi

echo "🔪 Killing $PACKAGE..."
go-ios kill "$PACKAGE" --udid="$SELECTED_DEVICE" &> /dev/null

if [[ "$RELAUNCH" == true ]]; then
  echo "🚀 Relaunching the app..."
  go-ios launch "$PACKAGE" --udid="$SELECTED_DEVICE" &> /dev/null
fi
