#!/bin/bash
LOCATION=$(dirname "$0")
source "$LOCATION"/../common_tools
ios_choose_device

echo "🔨 Launching system settings..."
go-ios launch "com.apple.Preferences" --udid="$SELECTED_DEVICE" &> /dev/null
