#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
ios_choose_device

UNINSTALL_COUNT=0
IGNORED_PACKAGES=( "com.thefuntasty.funtaster" "io.crash.air" "de.codenauts.hockeyapp" "ar.core" "com.framerjs.ios" "com.figma.mirror" "com.invisionapp.ifa") #TODO validate
ios_get_package_list

if [[  "$1" == "-a" ]]; then
  tput setaf 1
  should_proceed "💣 Delete all third party apps on $SELECTED_DEVICE_MODEL - $SELECTED_DEVICE?"
  tput sgr0
  for PKG in "${PACKAGE_LIST[@]}"
  do
    echo $IGNORED_PACKAGES | grep "$PKG" &> /dev/null && { echo "⏩ Skipped $PKG"; continue; }
    echo "🔥 Uninstalling $PKG"
    ideviceinstaller -u $SELECTED_DEVICE -U $PKG &> /dev/null
    ((++UNINSTALL_COUNT))
  done
  echo "✅ Apps uninstalled: $UNINSTALL_COUNT"
  exit
elif [[ -n "$1" ]]; then
  PACKAGE=$1
  echo $PACKAGE_LIST | grep -w "$PACKAGE" &> /dev/null || { echo "🤷‍ Package \"$PACKAGE\" not installed"; exit; }
  echo $IGNORED_PACKAGES | grep -w "$PACKAGE" &> /dev/null && { echo "🤷‍ Package \"$PACKAGE\" is whitelisted"; exit; }
fi

if [ -z "$PACKAGE" ]; then
  if [ ${#PACKAGE_LIST[@]} -eq 0 ]; then
      echo "🤷‍ Nothing to uninstall"
      exit
  fi

  echo "📋 Choose package number:"
  select OPTION in "${PACKAGE_LIST[@]}"
  do
   case $OPTION in
      *) PACKAGE=$OPTION;break; ;;
    esac
  done
fi

echo "🔥 Uninstalling $PACKAGE"
ideviceinstaller -u $SELECTED_DEVICE -U $PACKAGE &> /dev/null
echo "✅ Done"
