#!/bin/bash
LOCATION=$(dirname "$0")
source $LOCATION/../common_tools
ios_choose_device

select_option(){
    echo "📋 Choose package number:"
    select OPTION in "${PACKAGE_LIST[@]}"
    do
     case $OPTION in
        *) PACKAGE=$OPTION;break; ;;
      esac
    done
    if [[ -z $PACKAGE ]]; then
      echo "❌ Invalid option picked, retry"
      select_option
    fi
}

uninstall_package(){
  PACKAGE="$1"
  echo ${PACKAGES[*]} | grep -w "$PACKAGE" &> /dev/null || { echo "🤷‍ Package \"$PACKAGE\" not installed"; return; }
  echo ${IGNORED_PACKAGES[*]} | grep -w "$PACKAGE" &> /dev/null && { echo "❌ Package \"$PACKAGE\" is whitelisted"; return; }

  echo "🔥 Uninstalling $PACKAGE"
  ideviceinstaller -u $SELECTED_DEVICE -U $PKG &> /dev/null
}

UNINSTALL_COUNT=0
IGNORED_PACKAGES=( "com.apple.TestFlight" "com.thefuntasty.funtaster" "io.crash.air" "de.codenauts.hockeyapp" "com.framerjs.ios" "com.figma.mirror" "com.invisionapp.ifa")
ios_get_package_list

if [[  "$1" == "-a" ]]; then
  tput setaf 1
  should_proceed "💣 Delete all third party apps on $SELECTED_DEVICE_MODEL - $SELECTED_DEVICE?"
  tput sgr0
  for PKG in "${PACKAGE_LIST[@]}"
  do
    uninstall_package $PKG
    ((++UNINSTALL_COUNT))
  done
  echo "✅ Apps uninstalled: $UNINSTALL_COUNT"
  exit
elif [[ -n "$1" ]]; then
  uninstall_package $1
fi

if [ -z "$1" ]; then
  if [ ${#PACKAGE_LIST[@]} -eq 0 ]; then
      echo "🤷‍ Nothing to uninstall"
      exit
  fi
  select_option
fi

echo "✅ Done"
