name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Count lines of text in this repository
      run: git ls-files | xargs wc -l
    - name: Run a multi-line script
      run: |
        echo This is the end <3
